#!/bin/sh
set -ex

if [ -z ${BUILD_NUMBER} ]; then
  export BUILD_NUMBER=latest
fi


docker build -f Dockerfile-$PROJECT_ID -t gcr.io/${PROJECT_ID}/${APP_NAME}:${BUILD_NUMBER} .
gcloud docker -- push gcr.io/${PROJECT_ID}/${APP_NAME}:${BUILD_NUMBER}
